# Bibliotecas

In [17]:
"""
create table Produtos(
    ID INT,
    Nome NVARCHAR(255),
    Price money,
    Id_Category INT
)
"""

'\ncreate table Produtos(\n    ID INT,\n    Nome NVARCHAR(255),\n    Price money,\n    Id_Category INT\n)\n'

In [2]:
!pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\ketle\appdata\local\programs\python\python313\lib\site-packages (5.3.0)

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
import pandas as pd
import pyodbc

server = 'KETLEY'
database = 'Python'

conexaoDB = pyodbc.connect(
    'DRIVER={ODBC Driver 18 for SQL Server};'
    f'SERVER={server};'
    f'DATABASE={database};'
    'Trusted_Connection=yes;'
    'TrustServerCertificate=yes;'
)

cursor = conexaoDB.cursor()

print("Conectado com sucesso! 🚀")

Conectado com sucesso! 🚀

#### Conexão com senha

OperationalError: ('08001', '[08001] [Microsoft][ODBC Driver 18 for SQL Server]Interfaces de Rede do SQL Server: Erro ao Localizar Servidor/Instância Especificado [xFFFFFFFF].  (-1) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 18 for SQL Server]O tempo limite do logon expirou (0); [08001] [Microsoft][ODBC Driver 18 for SQL Server]Atributo de cadeia de conexão inválido (0); [08001] [Microsoft][ODBC Driver 18 for SQL Server]Ocorreu um erro relacionado à rede ou específico da instância ao estabelecer uma conexão com KETLEY\\Ketle. Servidor não encontrado ou não acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. Para mais informações, veja os Manuais Online do SQL Server. (-1)')

In [26]:
dados = pd.read_excel(r"C:\Users\Ketle\OneDrive\Documentos\Py_dados\Origem\arquivos_excel\Produto.xlsx")
dados.head(5)
#display(dados)

   ID                  Name  Price  Id_Category
0   0       Sapato vermelho     96            0
1   1  Bolsa mais que Velha   8000            0
2   2                 Calça     75            0
3   3    Camisa apertadinha    170            0
4   0       Sapato vermelho     96            0

In [14]:
dados.columns

Index(['ID', 'Name', 'Price', 'Id_Category'], dtype='str')

In [15]:
str(dados.columns).replace("'","")

'Index([ID, Name, Price, Id_Category], dtype=str)'

In [18]:
#Conversão de dados
dados['ID'] = dados.ID.astype(str)
dados['Name'] = dados.Name.astype(str)
dados['Price'] = dados.Price.astype(float)
dados['Id_Category'] = dados.Id_Category.astype(str)  ##conversao de dados para string nvarchar

# Inserindo DataFrame no Banco

In [19]:
dados.head(5)

  ID                  Name   Price Id_Category
0  0       Sapato vermelho    96.0           0
1  1  Bolsa mais que Velha  8000.0           0
2  2                 Calça    75.0           0
3  3    Camisa apertadinha   170.0           0
4  0       Sapato vermelho    96.0           0

In [28]:
for index, linha in dados.iterrows():
    
    cursor.execute("Insert into [Produtos](ID,Nome,Price,Id_Category)values(?,?,?,?)",linha.ID,linha.Name,linha.Price,linha.Id_Category) 
     # inserir colunas e quantas colunas tiver passar quantidade de ??
cursor.commit()   # validar dados no SQL Server
cursor.close()    #Fechar Cursor
conexaoDB.close() #Fechar Conexao

In [26]:
#cursor.execute('delete  from [dbo].[Dim_Produto]')   #executa tarefa de  apagar dados
#cursor.commit()